name: CI/CD backend
on:
  push:
    branches: ["maIN"]
jobs:
  build:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jualInd-be:latest

  deployment:
    needs: build
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e # Exit immediately if a command exits with a non-zero status

            echo "Current user: $(whoami)"

            echo "Pulling the latest image from Docker Hub..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/jualInd-be:latest


        
            echo "Starting backend container..."
            docker run -d --name jualIND-api -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/jualInd-be:latest:latest
          